import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#bbcabf',
        'on-primary-container': '#00422b',
        'primary-fixed': '#6ffbbe',
        'on-secondary-fixed-variant': '#004c6e',
        'on-secondary-container': '#00344e',
        'primary-fixed-dim': '#4edea3',
        'surface-container-low': '#191c1f',
        'on-background': '#e1e2e7',
        'primary-container': '#10b981',
        'on-surface': '#e1e2e7',
        'surface-variant': '#323539',
        'surface-container-high': '#282a2e',
        secondary: '#89ceff',
        background: '#111417',
        'on-primary-fixed-variant': '#005236',
        'on-tertiary-container': '#711419',
        'inverse-surface': '#e1e2e7',
        'secondary-container': '#00a2e6',
        'on-error-container': '#ffdad6',
        error: '#ffb4ab',
        'tertiary-fixed': '#ffdad7',
        'tertiary-container': '#fc7c78',
        'inverse-primary': '#006c49',
        'surface-tint': '#4edea3',
        'inverse-on-surface': '#2e3134',
        outline: '#86948a',
        'on-tertiary-fixed': '#410005',
        'on-secondary-fixed': '#001e2f',
        'outline-variant': '#3c4a42',
        'surface-container-lowest': '#0c0e12',
        'surface-dim': '#111417',
        'surface-container-highest': '#323539',
        'on-tertiary-fixed-variant': '#842225',
        'on-error': '#690005',
        'on-primary-fixed': '#002113',
        'error-container': '#93000a',
        'surface-container': '#1d2023',
        'tertiary-fixed-dim': '#ffb3af',
        primary: '#4edea3',
        'secondary-fixed': '#c9e6ff',
        surface: '#111417',
        'on-tertiary': '#650911',
        'secondary-fixed-dim': '#89ceff',
        tertiary: '#ffb3af',
        'on-primary': '#003824',
        'surface-bright': '#37393d',
        'on-secondary': '#00344d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '80px',
        'section-gap': '160px',
        unit: '4px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'headline-md': ['var(--font-plus-jakarta)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-plus-jakarta)', 'sans-serif'],
        'display-lg': ['var(--font-plus-jakarta)', 'sans-serif'],
        'label-caps': ['var(--font-inter)', 'sans-serif'],
        'mono-technical': ['var(--font-inter)', 'sans-serif'],
        'headline-lg': ['var(--font-plus-jakarta)', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '0.05em', fontWeight: '800' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.15em', fontWeight: '700' }],
        'mono-technical': ['14px', { lineHeight: '1.5', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}

export default config
